### ISSUE TITLE
What version of opencv do you use?

### ISSUE THREAD

**Issue by day-dreaming-guy** [edolev89/stitch-it#1]
What version of opencv do you use?

It not compiling for me, getting:
```
Traceback (most recent call last):
  File "/Users/nirendy/Downloads/stitch-it-master/pic_stitch.py", line 22, in <module>
    stitched = stitch(images)
  File "/Users/nirendy/Downloads/stitch-it-master/utils.py", line 29, in stitch
    stitcher = cv2.createStitcher()
AttributeError: module 'cv2' has no attribute 'createStitcher'
```

**Comment by denis-cognimade** [comment]
Did you found a solution to this? I've got the same exact error.
`opencv3` library from README does not exists and `opencv-python` seems not the correct one.


<details>
<summary>Console log</summary>

```cmd
(.venv) c:\Development\scripts\capture-page\stitch-it>python vid_stitch.py -v ..\Video.mp4  
Traceback (most recent call last):
  File "c:\Development\scripts\capture-page\stitch-it\vid_stitch.py", line 1, in <module> 
    import cv2  
ModuleNotFoundError: No module named 'cv2'

(.venv) c:\Development\scripts\capture-page\stitch-it>pip install opencv3
ERROR: Could not find a version that satisfies the requirement opencv3 (from versions: none)
ERROR: No matching distribution found for opencv3

(.venv) c:\Development\scripts\capture-page\stitch-it>pip install opencv-python
Collecting opencv-python
  Downloading opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting numpy>=1.21.2 (from opencv-python)
  Downloading numpy-2.2.5-cp312-cp312-win_amd64.whl.metadata (60 kB)
Downloading opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl (39.5 MB)
  ---------------------------------------- 39.5/39.5 MB 10.2 MB/s eta 0:00:00
Downloading numpy-2.2.5-cp312-cp312-win_amd64.whl (12.6 MB)
  ---------------------------------------- 12.6/12.6 MB 11.0 MB/s eta 0:00:00
Installing collected packages: numpy, opencv-python 
Successfully installed numpy-2.2.5 opencv-python-4.11.0.86

(.venv) c:\Development\scripts\capture-page\stitch-it>python vid_stitch.py -v ..\Video.mp4  
Traceback (most recent call last):
  File "c:\Development\scripts\capture-page\stitch-it\vid_stitch.py", line 23, in <module>
    stitched = stitch(images)
               ^^^^^^^^^^^^^^
  File "c:\Development\scripts\capture-page\stitch-it\utils.py", line 29, in stitch
    stitcher = cv2.createStitcher()
               ^^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2' has no attribute 'createStitcher' 

(.venv) c:\Development\scripts\capture-page\stitch-it>

```
</details>
